version: '3'
services:
  nest-app:
    build: .
    ports:
      - '3080:3080'
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
      - minio

  redis:
    image: 'redis:alpine3.16'
    ports:
      - '6379:6379'
  
  minio:
    image: 'minio/minio'
    ports:
      - '9000:9000'
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - './minio-data:/data'
      - './minio-config:/root/.minio'
    command: server /data